# Generated by Django 5.1.3 on 2024-12-02 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceDetec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='face_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
