# Generated by Django 4.1 on 2024-12-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceDetec', '0002_attendance_face_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='face_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
